export const WHATSAPP_CALLS_API = [
  {
    id: 1,
    first_name: 'Glenn',
    missed: true,
    date: '22-Mar-2016',
    time: '5:46 PM',
    image: 'https://randomuser.me/api/portraits/women/1.jpg',
  },
  {
    id: 2,
    first_name: 'Carl',
    missed: true,
    date: '22-Feb-2016',
    time: '09:38 PM',
    image: 'https://randomuser.me/api/portraits/women/2.jpg',
  },
  {
    id: 3,
    first_name: 'Rick',
    missed: false,
    date: '01-Jul-2016',
    time: '1:33 PM',
    image: 'https://randomuser.me/api/portraits/women/3.jpg',
  },
  {
    id: 4,
    first_name: 'Maggie',
    missed: false,
    date: '19-Feb-2016',
    time: '02:59 AM',
    image: 'https://randomuser.me/api/portraits/women/4.jpg',
  },
  {
    id: 5,
    first_name: 'Michael',
    missed: true,
    date: '12-Aug-2016',
    time: '9:17 AM',
    image: 'https://randomuser.me/api/portraits/women/5.jpg',
  },
  {
    id: 6,
    first_name: 'Jesus',
    missed: false,
    date: '13-Aug-2016',
    time: '10:37 PM',
    image: 'https://randomuser.me/api/portraits/women/6.jpg',
  },
  {
    id: 7,
    first_name: 'Daryn',
    missed: true,
    date: '17-Nov-2016',
    time: '07:32 AM',
    image: 'https://randomuser.me/api/portraits/women/7.jpg',
  },
  {
    id: 8,
    first_name: 'Fred',
    missed: false,
    date: '29-Nov-2016',
    time: '12:56 AM',
    image: 'https://randomuser.me/api/portraits/women/8.jpg',
  },
  {
    id: 9,
    first_name: 'James',
    missed: false,
    date: '27-Dec-2016',
    time: '9:29 PM',
    image: 'https://randomuser.me/api/portraits/women/9.jpg',
  },
  {
    id: 10,
    first_name: 'Matthew',
    missed: true,
    date: '31-Dec-2016',
    time: '7:43 PM',
    image: 'https://randomuser.me/api/portraits/women/10.jpg',
  },
];
export const WHATSAPP_CHATS_API = [
  {
    id: 1,
    first_name: 'Glenn',
    read: true,
    message: 'Where are you now?',
    date: '22-Mar-2016',
    time: '5:46 PM',
    image: 'https://randomuser.me/api/portraits/men/1.jpg',
  },
  {
    id: 2,
    first_name: 'Carl',
    read: false,
    message: 'Do you smell what the rock is cooking?',
    date: '22-Feb-2016',
    time: '09:38 PM',
    image: 'https://randomuser.me/api/portraits/men/2.jpg',
  },
  {
    id: 3,
    first_name: 'Rick',
    read: true,
    message: "Hello there it's been a while. Not much",
    date: '01-Jul-2016',
    time: '1:33 PM',
    image: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
  {
    id: 4,
    first_name: 'Maggie',
    read: false,
    message: 'Oh Baby, baby baby... my baby baby',
    date: '19-Feb-2016',
    time: '02:59 AM',
    image: 'https://randomuser.me/api/portraits/women/23.jpg',
  },
  {
    id: 5,
    first_name: 'Michael',
    read: true,
    message: 'Extreme fishing with Robson green',
    date: '12-Aug-2016',
    time: '9:17 AM',
    image: 'https://randomuser.me/api/portraits/men/13.jpg',
  },
  {
    id: 6,
    first_name: 'Jesus',
    read: false,
    message: "Why do people care about marcos' burial in LBNM",
    date: '13-Aug-2016',
    time: '10:37 PM',
    image: 'https://randomuser.me/api/portraits/men/33.jpg',
  },
  {
    id: 7,
    first_name: 'Daryn',
    read: true,
    message: 'Simply amazing, brilliant and absolutely fantastic',
    date: '17-Nov-2016',
    time: '07:32 AM',
    image: 'https://randomuser.me/api/portraits/women/6.jpg',
  },
  {
    id: 8,
    first_name: 'Fred',
    read: false,
    message: 'Saw you this morning and i wake up shitty.',
    date: '29-Nov-2016',
    time: '12:56 AM',
    image: 'https://randomuser.me/api/portraits/men/7.jpg',
  },
  {
    id: 9,
    first_name: 'James',
    read: false,
    message: 'I will never walk alone',
    date: '27-Dec-2016',
    time: '9:29 PM',
    image: 'https://randomuser.me/api/portraits/men/9.jpg',
  },
  {
    id: 10,
    first_name: 'Matthew',
    read: true,
    message: 'Got it',
    date: '31-Dec-2016',
    time: '7:43 PM',
    image: 'https://randomuser.me/api/portraits/men/12.jpg',
  },
];
export const WHATSAPP_CONTACTS_API = [
  {
    id: 1,
    first_name: 'Glenn',
    mobile: true,
    message: 'Hey there! I am using WhatsApp',
    date: '22-Mar-2016',
    time: '5:46 PM',
    image: 'https://randomuser.me/api/portraits/men/1.jpg',
    stories: [
      {
        id: 1,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 3, 4],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
      {
        id: 2,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 3, 4],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
    ],
  },
  {
    id: 2,
    first_name: 'Carl',
    mobile: false,
    message: 'Do you smell what the rock is cooking?',
    date: '22-Feb-2016',
    time: '09:38 PM',
    image: 'https://randomuser.me/api/portraits/women/37.jpg',
    stories: [
      {
        id: 1,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [5, 3, 4],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
      {
        id: 2,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [1, 3, 4],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
    ],
  },
  {
    id: 3,
    first_name: 'Rick',
    mobile: true,
    message: "Hello there it's been a while. Not much",
    date: '01-Jul-2016',
    time: '1:33 PM',
    image: 'https://randomuser.me/api/portraits/women/13.jpg',
    stories: [
      {
        id: 1,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 4, 5],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
      {
        id: 2,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 4, 5],
        image: 'https://randomuser.me/api/portraits/women/13.jpg',
      },
    ],
  },
  {
    id: 4,
    first_name: 'Maggie',
    mobile: false,
    message: 'Oh Baby, baby baby... my baby baby',
    date: '19-Feb-2016',
    time: '02:59 AM',
    image: 'https://randomuser.me/api/portraits/men/5.jpg',
    stories: [
      {
        id: 1,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 3, 5],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
      {
        id: 2,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 3, 5],
        image: 'https://randomuser.me/api/portraits/women/13.jpg',
      },
    ],
  },
  {
    id: 5,
    first_name: 'Michael',
    mobile: true,
    message: 'Extreme fishing with Robson green',
    date: '12-Aug-2016',
    time: '9:17 AM',
    image: 'https://randomuser.me/api/portraits/men/19.jpg',
    stories: [
      {
        id: 1,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 4, 1],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
      {
        id: 2,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 4, 1],
        image: 'https://randomuser.me/api/portraits/women/13.jpg',
      },
    ],
  },
  {
    id: 6,
    first_name: 'Jesus',
    mobile: false,
    message: "Why do people care about marcos' burial in LBNM",
    date: '13-Aug-2016',
    time: '10:37 PM',
    image: 'https://randomuser.me/api/portraits/men/18.jpg',
    stories: [
      {
        id: 1,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [3, 4, 8],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
      {
        id: 2,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 4, 1],
        image: 'https://randomuser.me/api/portraits/women/13.jpg',
      },
    ],
  },
  {
    id: 7,
    first_name: 'Daryn',
    mobile: true,
    message: 'Simply amazing, brilliant and absolutely fantastic',
    date: '17-Nov-2016',
    time: '07:32 AM',
    image: 'https://randomuser.me/api/portraits/men/30.jpg',
    stories: [
      {
        id: 1,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 4, 1],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
      {
        id: 2,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 4, 1],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
    ],
  },
  {
    id: 8,
    first_name: 'Fred',
    mobile: false,
    message: 'Saw you this morning and i wake up shitty.',
    date: '29-Nov-2016',
    time: '12:56 AM',
    image: 'https://randomuser.me/api/portraits/women/10.jpg',
    stories: [
      {
        id: 1,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 4, 1],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
      {
        id: 2,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 4, 1],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
    ],
  },
  {
    id: 9,
    first_name: 'James',
    mobile: false,
    message: 'I will never walk alone',
    date: '27-Dec-2016',
    time: '9:29 PM',
    image: 'https://randomuser.me/api/portraits/women/6.jpg',
    stories: [
      {
        id: 1,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 4, 1],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
      {
        id: 2,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 4, 1],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
    ],
  },
  {
    id: 10,
    first_name: 'Matthew',
    mobile: true,
    message: 'Got it',
    date: '31-Dec-2016',
    time: '7:43 PM',
    image: 'https://randomuser.me/api/portraits/men/18.jpg',
    stories: [
      {
        id: 1,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 4, 1],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
      {
        id: 2,
        createdAt: new Date(Date.now() - 24 * 60 * 1000 * 1000),
        viewedBy: [2, 4, 1],
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
      },
    ],
  },
];
